/** Declaration file generated by dts-gen */

export = attempt_promise;

declare function attempt_promise(promise: any): any;

declare namespace attempt_promise {
    function all(promises: any): any;

}

